[package]
name = "fan455_math_scalar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4.5"
num-traits = "0.2.18"

[features]
